apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: aws-code-pipeline
    app.kubernetes.io/instance: aws-code-pipeline-instance
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/managed-by: kubectl
  name: aws-code-pipeline-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: aws-code-pipeline
  template:
    metadata:
      labels:
        app: aws-code-pipeline
    spec:
      containers:
        - image: 469427049902.dkr.ecr.ap-northeast-1.amazonaws.com/demo-ecr-repo:TAG_VERSION
          imagePullPolicy: Always
          name: aws-code-pipeline
          ports:
            - containerPort: 80